[package]
name = "yi-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
yi-types = { workspace = true }
miniz_oxide = { workspace = true }
serde_json = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
zeromq = { workspace = true }
thiserror = { workspace = true }
ureq = { workspace = true }

[build-dependencies]
miniz_oxide = { workspace = true }
