[package]
name = "yi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
yi-types = { workspace = true }
yi-runtime = { workspace = true }
yi-mcp-cli = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
lexopt = { workspace = true }

[[bin]]
name = "yi"
path = "src/main.rs"
