[package]
name = "yi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
yi-types = { workspace = true }
yi-runtime = { workspace = true }
yi-acp = { workspace = true }
yi-tui = { workspace = true, optional = true }
yi-console = { workspace = true, optional = true }
yi-mcp-cli = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
lexopt = { workspace = true }

[dev-dependencies]
yi-tools = { workspace = true }

[features]
default = ["tui"]
tui = ["dep:yi-tui", "dep:yi-console"]

[[bin]]
name = "yi"
path = "src/main.rs"
