//! F0b, import: format 1 becomes format 2 explicitly and losslessly.
//!
//! Test plan. Import is `Op::Import`, never a side effect of a read. The importer
//! reads and validates the old file, stores the original bytes as an immutable
//! artifact under `artifacts/<sha256>` written with `create_new`, converts the
//! frontmatter, maps each `## <label>` body section to `todos[].note` up to 4 KiB
//! and a larger one to an artifact reference (never a cut), keeps unknown fields
//! under `extra` with provenance, maps `Check::Command` to one critical `cmd`
//! item marked `revalidate` and `Check::Stated` to a `LegacyUnverified`
//! requirement kept verbatim, imports todos already `Done` as history, writes the
//! genesis `import` record carrying the original digest and the mapping, and
//! writes `plan.json` last. The original `.md` stays on disk until a separate,
//! user confirmed cleanup.
//!
//! The contract mapping is F0c's: this stage keeps `Delegation.accept` verbatim,
//! which is the input that mapping reads, and pins that it survives the trip.
//!
//! What `plan/import.rs` does, since the comment ratchet keeps the file itself
//! terse. `run` resolves the `local://` source against the engine's cwd (any
//! other scheme, and any hashline fragment, is a refusal, because the importer
//! reads a file and never fetches a reference); reads it under one
//! `IMPORT_CAP_BYTES` cap, which both it and `read_legacy` take, so a huge body
//! is a named refusal rather than a shortened document; refuses a frontmatter
//! over the 32 KiB `PLAN_CAP_BYTES` cap before serde sees it; parses format 1
//! through `Plan::parse_legacy`, which accepts format 1 alone; refuses a plan
//! that already has a format-2 checkpoint; writes the original bytes to
//! `artifacts/<sha256>`; then maps the sections. A section at or under the
//! 4 KiB `NOTE_MAX_BYTES` becomes `todos[].note`; a longer one becomes its own
//! blob and the todo carries `note_ref` in `extra` as `artifact:sha256:<hex>`,
//! so nothing is cut and no offset is ever taken into a `str`. Unknown keys
//! ride `extra` as the reader left them; the provenance of the conversion is
//! the genesis record, never a key in `plan.json`, which is why the expected
//! checkpoint below carries no import marker of its own.
//!
//! Crash matrix. Import is one transaction over the same commit protocol as any
//! other op, so the rows are the journal's rows read through the importer.
//!
//! | crash point | expected recovery | pinned by |
//! |---|---|---|
//! | after the artifact blob is written, before the `import` record commits | nothing was imported: the blob is an orphan under `artifacts/`, addressed by digest, and the retry writes the identical bytes (`create_new` on an existing identical digest is not an error the import fails on) | `import_preserves_all_markdown_and_large_notes` |
//! | after the `import` record commits, before `plan.json` is written | imported: the checkpoint is regenerated by reducing the journal, and the format-1 file is still on disk and still untouched | `plan_recovery::recovery_reduces_events_without_dispatching_effects` |
//! | after the whole import, on a binary two releases newer | the format-1 reader is kept for two releases, so a skipped release still imports rather than refusing the file | `skipped_release_can_still_import_format_one` |
//! | never: a read of a format-1 file | read-only, with a notice naming `yi plan import <id>`; no record, no blob, no conversion | `plan_store::a_format_1_read_is_read_only_until_import` |
//!
//! Fixtures this file reads: `fixtures/plans/format1/campaign.md` (exactly what
//! the campaign walkthrough writes today, sha256
//! `00d2b1d18888b753ed61db90efefada70e92af05096d07c361489ca1d7cc1987`), the
//! expected `fixtures/plans/format2/campaign/` (`plan.json` and the genesis
//! `ops.jsonl`), and `fixtures/plans/format1/large-section.md`, whose one body
//! section is 6,144 bytes and must land as an artifact reference.

#[path = "../../types/tests/support/scratch.rs"]
mod scratch;
use scratch::Scratch;

use std::error::Error;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use serde_json::Value;
use yi_runtime::plan::import::{self, ImportError, NOTE_REF_KEY};
use yi_runtime::plan::journal::Clock;
use yi_runtime::plan::ops::{Actor, Delegate, Op, OpRequest, PlanEngine};
use yi_runtime::plan::store::{PlanStore, StoreError};
use yi_types::plan::canonical::Digest;
use yi_types::plan::contract::Resolution;
use yi_types::plan::doc::{
    AgentId, Check, Delegation, PLAN_FORMAT, Plan, PlanId, TodoAddr, TodoLabel, TodoState,
};
use yi_types::plan::ledger::RequestId;
use yi_types::url::Url;

type TestResult = Result<(), Box<dyn Error>>;

/// The genesis record's `at`: the fixture's wall clock, so the journal bytes are the fixture's.
const FIXED_MS: u64 = 1_757_650_000_000;

struct Frozen;

impl Clock for Frozen {
    fn now_ms(&self) -> u64 {
        FIXED_MS
    }
}

struct NoChildren;

impl Delegate for NoChildren {
    fn spawn(&self, _at: &TodoAddr, _delegation: &Delegation) -> Result<AgentId, String> {
        Err("this test never spawns".to_owned())
    }

    fn reap(&self, _agent: &AgentId, _supplied: &[Url]) -> Result<Option<Url>, String> {
        Ok(None)
    }

    fn follow_up(&self, _dispatched: &[TodoLabel], _held: usize) {}
}

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/plans")
}

/// A workspace whose `.yi/plans` holds the legacy file, so the source url is the relative
/// `local://.yi/plans/<id>.md` a user or the CLI would name.
struct Rig {
    _dir: Scratch,
    cwd: PathBuf,
    store: PlanStore,
    engine: PlanEngine,
}

fn rig(name: &str) -> Result<Rig, Box<dyn Error>> {
    let dir = Scratch::new(&format!("yi-plan-import-{name}"))?;
    let cwd = dir.to_path_buf();
    let plans = cwd.join(".yi/plans");
    std::fs::create_dir_all(&plans)?;
    let store = PlanStore::open(plans)?.with_clock(Arc::new(Frozen));
    let engine = PlanEngine::new(store.clone(), Arc::new(NoChildren)).with_cwd(cwd.clone());
    Ok(Rig {
        _dir: dir,
        cwd,
        store,
        engine,
    })
}

impl Rig {
    /// Put a format-1 document where `yi plan import <id>` would find it and return its url.
    fn legacy(&self, id: &PlanId, text: &str) -> Result<Url, Box<dyn Error>> {
        std::fs::write(self.store.dir().join(format!("{id}.md")), text)?;
        Ok(format!("local://.yi/plans/{id}.md").parse::<Url>()?)
    }

    fn import(&self, source: &Url, request_id: &str) -> Result<(), Box<dyn Error>> {
        self.engine.apply(OpRequest {
            plan: None,
            actor: Actor::Owner,
            op: Op::Import {
                source: source.clone(),
            },
            request_id: Some(RequestId::new(request_id)?),
            expected_revision: None,
        })?;
        Ok(())
    }
}

/// Every byte of the original survives as a blob, the converted checkpoint and its genesis
/// record are the fixtures byte for byte, the `.md` is left where it was, and a body section
/// over the 4 KiB note cap lands whole as an artifact reference rather than a cut note.
/// Dies with the shape hold in the import's reduce (`state.rs`): a worktree todo here has no
/// contract, and `validate_plan` there refuses the replay of its own genesis record.
#[test]
fn import_preserves_all_markdown_and_large_notes() -> TestResult {
    let rig = rig("campaign")?;
    let id = PlanId::new("ship-logrotate-lite-with-a-packaged")?;
    let original = std::fs::read(fixtures().join("format1/campaign.md"))?;
    let source = rig.legacy(&id, std::str::from_utf8(&original)?)?;

    rig.import(&source, "r-7f3a-1")?;

    let expected = fixtures().join("format2/campaign");
    assert_eq!(
        std::fs::read(rig.store.path(&id))?,
        std::fs::read(expected.join("plan.json"))?,
        "the checkpoint is the expected format-2 document byte for byte"
    );
    assert_eq!(
        std::fs::read(rig.store.journal_path(&id))?,
        std::fs::read(expected.join("ops.jsonl"))?,
        "the genesis import record is the expected journal byte for byte"
    );

    let legacy = rig.store.dir().join(format!("{id}.md"));
    assert_eq!(
        std::fs::read(&legacy)?,
        original,
        "the original is left in place, untouched, until a confirmed cleanup"
    );
    let digest = Digest::of(&original);
    assert_eq!(
        digest.to_string(),
        "sha256:00d2b1d18888b753ed61db90efefada70e92af05096d07c361489ca1d7cc1987",
        "the fixture's bytes are the digest the genesis record names"
    );
    assert_eq!(
        rig.store.artifacts(&id).get(&digest)?,
        original,
        "the original bytes are readable from the blob by digest"
    );

    let imported = rig.store.read(&id)?;
    assert_eq!(imported.todos.len(), 2);
    for todo in &imported.todos {
        assert!(
            matches!(todo.state, TodoState::Done { .. }),
            "a todo already done imports as done and stays visible as history"
        );
        assert!(todo.note.is_none(), "campaign has no body sections");
    }

    // The orphan-blob row of the crash matrix: a retry writes the identical bytes and the
    // existing blob is not an error the import fails on.
    let again =
        rig.store
            .artifacts(&id)
            .put(&original, import::MARKDOWN_MEDIA_TYPE, &rig.store.nonce())?;
    assert_eq!(again.digest, digest);

    // A second import of the same source is refused: the plan is format 2 now.
    match rig.import(&source, "r-7f3a-2") {
        Err(error) => assert!(
            error.to_string().contains("already format 2"),
            "expected an already-imported refusal, got {error}"
        ),
        Ok(()) => return Err("a second import must be refused".into()),
    }

    large_section(&rig)
}

/// Every `done` a format-1 file claims imports as `LegacyUnverified`: history the view shows
/// by name, never evidence a later completion can lean on.
#[test]
fn legacy_done_imports_as_legacy_unverified() -> TestResult {
    let rig = rig("legacy-unverified")?;
    let id = PlanId::new("ship-logrotate-lite-with-a-packaged")?;
    let original = std::fs::read_to_string(fixtures().join("format1/campaign.md"))?;
    let source = rig.legacy(&id, &original)?;
    rig.import(&source, "r-legacy-1")?;
    let viewed = rig.engine.apply(OpRequest {
        plan: Some(id.clone()),
        actor: Actor::Owner,
        op: Op::View { full: true },
        request_id: None,
        expected_revision: None,
    })?;
    assert_eq!(viewed.plan.todos.len(), 2);
    for todo in &viewed.plan.todos {
        assert!(
            matches!(
                todo.state,
                TodoState::Done {
                    resolution: Some(Resolution::LegacyUnverified),
                    ..
                }
            ),
            "{}: {:?}",
            todo.label,
            todo.state
        );
    }
    let rendered = PlanStore::render(&viewed.plan)?;
    assert_eq!(
        rendered
            .matches("\"resolution\": \"legacy_unverified\"")
            .count(),
        2,
        "{rendered}"
    );
    assert!(
        !rendered.contains("verified_done") && !rendered.contains("accepted_by_user"),
        "{rendered}"
    );
    Ok(())
}

/// The 6 KiB section: whole into a blob, named from the todo, and never inlined or cut.
fn large_section(rig: &Rig) -> TestResult {
    let id = PlanId::new("vendor-the-zstd-backend")?;
    let path = fixtures().join("format1/large-section.md");
    let original = std::fs::read_to_string(&path)?;
    let source = rig.legacy(&id, &original)?;
    rig.import(&source, "r-7f3a-3")?;

    let imported = rig.store.read(&id)?;
    let noted = imported
        .todos
        .first()
        .ok_or("the imported plan kept no todos")?;
    assert_eq!(noted.label.as_str(), "Write the rotation contract note");
    assert!(
        noted.note.is_none(),
        "a section over the 4 KiB note cap is never inlined"
    );
    let reference = noted
        .extra
        .get(NOTE_REF_KEY)
        .and_then(Value::as_str)
        .ok_or("the long section left no artifact reference")?;

    let body = import::parse_document(&original)?.body;
    let section = import::section_of(&body, noted.label.as_str())
        .ok_or("the fixture lost its body section")?;
    assert!(
        section.len() > 4096,
        "the fixture's section is {} bytes, which no longer exceeds the note cap",
        section.len()
    );
    let digest = Digest::of(section.as_bytes());
    assert_eq!(
        reference,
        format!("artifact:{digest}"),
        "the reference addresses the blob by digest"
    );
    assert_eq!(
        rig.store.artifacts(&id).get(&digest)?,
        section.as_bytes(),
        "the section is stored whole, not cut and not sliced mid-character"
    );

    let bare = imported
        .todos
        .get(1)
        .ok_or("the imported plan lost its second todo")?;
    assert!(
        bare.note.is_none() && !bare.extra.contains_key(NOTE_REF_KEY),
        "a todo with no body section gets neither a note nor a reference"
    );
    assert!(
        matches!(
            bare.delegation
                .as_ref()
                .map(|delegation| &delegation.accept),
            Some(Check::Command(_))
        ),
        "Delegation.accept is kept verbatim for F0c to turn into a contract"
    );
    assert!(
        matches!(
            noted
                .delegation
                .as_ref()
                .map(|delegation| &delegation.accept),
            Some(Check::Stated(_))
        ),
        "a stated acceptance is kept verbatim too"
    );
    Ok(())
}

/// The format-1 reader is kept for two releases: a build whose `PLAN_FORMAT` has already moved
/// to 2 still reads and imports a format-1 file rather than refusing it, and every key it does
/// not know survives the conversion under `extra`.
#[test]
fn skipped_release_can_still_import_format_one() -> TestResult {
    let rig = rig("skipped")?;
    let id = PlanId::new("vendor-the-zstd-backend")?;
    let front = r#"{
  "format": 1,
  "plan": "vendor-the-zstd-backend",
  "goal": "Vendor the zstd backend",
  "version": 1,
  "touched": 3,
  "tier": "root",
  "state": "active",
  "campaign": "logrotate",
  "todos": [
    {"label": "Pin the version", "state": "pending", "origin": "a release this build never saw"}
  ]
}"#;
    let source = rig.legacy(
        &id,
        &format!("---\n{front}\n---\n## Pin the version\nprose\n"),
    )?;

    assert!(
        matches!(rig.store.read(&id), Err(StoreError::NeedsImport { .. })),
        "the format-2 read path refuses the file and names the import"
    );
    assert!(
        serde_json::from_str::<Plan>(front).is_err(),
        "the format-2 parser refuses format 1, so the legacy reader is a kept path of its own"
    );
    assert!(
        import::read_legacy(&rig.store, &id).is_ok(),
        "the legacy reader still accepts it"
    );

    rig.import(&source, "r-skip-1")?;

    let imported = rig.store.read(&id)?;
    assert_eq!(
        imported.extra.get("campaign").and_then(Value::as_str),
        Some("logrotate"),
        "an unknown frontmatter key survives under extra"
    );
    let todo = imported.todos.first().ok_or("the todo was lost")?;
    assert_eq!(
        todo.extra.get("origin").and_then(Value::as_str),
        Some("a release this build never saw"),
        "an unknown todo key survives under extra"
    );
    assert_eq!(
        todo.note.as_ref().map(yi_types::plan::doc::Note::as_str),
        Some("## Pin the version\nprose"),
        "the body section became the todo's note"
    );

    let checkpoint: Value = serde_json::from_slice(&std::fs::read(rig.store.path(&id))?)?;
    assert_eq!(
        checkpoint.get("format").and_then(Value::as_u64),
        Some(u64::from(PLAN_FORMAT)),
        "what was written is format 2"
    );
    Ok(())
}

/// The journal, not the checkpoint file, says whether a plan exists: a retry of a committed
/// import with its own request id replays, and an import over a plan whose `plan.json` was
/// lost behind a live journal is refused with the journal untouched.
#[test]
fn a_retried_import_replays_and_a_lost_checkpoint_cannot_be_imported_over() -> TestResult {
    let rig = rig("replay")?;
    let id = PlanId::new("replayed")?;
    let source = rig.legacy(
        &id,
        "---\n{\"format\": 1, \"plan\": \"replayed\", \"goal\": \"g\", \"version\": 1, \"tier\": \"root\", \"state\": \"active\", \"todos\": [{\"label\": \"cut\", \"state\": \"pending\"}]}\n---\n",
    )?;
    let import = |request_id: &str| -> Result<_, Box<dyn Error>> {
        Ok(rig.engine.apply(OpRequest {
            plan: None,
            actor: Actor::Owner,
            op: Op::Import {
                source: source.clone(),
            },
            request_id: Some(RequestId::new(request_id)?),
            expected_revision: None,
        })?)
    };
    import("r-7f3a-9")?;
    std::fs::remove_file(rig.store.path(&id))?;
    let again = import("r-7f3a-9")?;
    assert!(
        again
            .notices
            .iter()
            .any(|notice| notice.contains("replayed")),
        "{:?}",
        again.notices
    );
    assert!(
        rig.store.path(&id).is_file(),
        "the checkpoint is regenerated"
    );
    assert_eq!(
        rig.store.journal(&id).read()?.records.len(),
        1,
        "one import, replayed"
    );

    rig.engine.apply(OpRequest {
        plan: Some(id.clone()),
        actor: Actor::Owner,
        op: Op::Drop {
            label: TodoLabel::new("cut")?,
            disposition: None,
        },
        request_id: None,
        expected_revision: None,
    })?;
    let journal_before = std::fs::read(rig.store.journal_path(&id))?;
    std::fs::remove_file(rig.store.path(&id))?;
    match import("r-7f3a-10") {
        Err(error) => assert!(
            error.to_string().contains("already format 2"),
            "expected an already-imported refusal, got {error}"
        ),
        Ok(_) => return Err("an import over a live journal must be refused".into()),
    }
    assert_eq!(
        std::fs::read(rig.store.journal_path(&id))?,
        journal_before,
        "the journal is untouched"
    );
    let plan = rig.store.read(&id)?;
    assert!(
        matches!(plan.todos[0].state, TodoState::Abandoned),
        "the drop stands: {:?}",
        plan.todos[0].state
    );
    Ok(())
}

/// The source is a file this process reads, not a reference it fetches, and the whole document
/// takes one cap before any parse.
#[test]
fn an_unfetchable_source_and_an_oversized_document_are_refused() -> TestResult {
    let rig = rig("bounds")?;
    let remote = "https://example.invalid/plan.md".parse::<Url>()?;
    match import::read(&rig.cwd, &remote) {
        Err(ImportError::NotLocal { .. }) => {}
        other => return Err(format!("expected NotLocal, got {other:?}").into()),
    }

    let id = PlanId::new("oversized")?;
    let mut text = String::from(
        "---\n{\"format\": 1, \"plan\": \"oversized\", \"goal\": \"g\", \"version\": 1, \"tier\": \"root\", \"state\": \"active\"}\n---\n",
    );
    text.push_str(&"x".repeat(import::IMPORT_CAP_BYTES));
    let source = rig.legacy(&id, &text)?;
    match import::read(&rig.cwd, &source) {
        Err(ImportError::OverCap { cap, .. }) => assert_eq!(cap, import::IMPORT_CAP_BYTES),
        other => return Err(format!("expected OverCap, got {other:?}").into()),
    }
    assert!(
        !rig.store.plan_dir(&id).exists(),
        "an oversized document writes no blob and no checkpoint"
    );
    Ok(())
}

/// A document with a repeated label or an edge to no todo is refused by the domain validator
/// before any blob or record, so an invalid graph never becomes the journal genesis.
#[test]
fn an_invalid_graph_is_refused_before_the_genesis_record() -> TestResult {
    let rig = rig("invalid-graph")?;
    let id = PlanId::new("twice")?;
    let text = "---\n{\"format\": 1, \"plan\": \"twice\", \"goal\": \"g\", \"version\": 1, \"tier\": \"root\", \"state\": \"active\", \"todos\": [{\"label\": \"same\", \"state\": \"pending\"}, {\"label\": \"same\", \"state\": \"pending\"}, {\"label\": \"late\", \"state\": \"pending\", \"after\": [\"ghost\"]}]}\n---\n";
    let source = rig.legacy(&id, text)?;
    let refused = rig.import(&source, "r-invalid");
    assert!(
        refused
            .as_ref()
            .is_err_and(|error| error.to_string().contains("same")),
        "{refused:?}"
    );
    assert!(
        !rig.store.plan_dir(&id).exists(),
        "an invalid document writes no blob and no record"
    );
    Ok(())
}
