[package]
name = "yi-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json.workspace = true
globset.workspace = true
regex.workspace = true
thiserror.workspace = true
xxhash-rust.workspace = true
yi-permission.workspace = true
yi-types.workspace = true

[lints]
workspace = true
