# yi(1) fish completion. Static: lexopt has no generator (X10).
complete -c yi -f
complete -c yi -n __fish_use_subcommand -a ask -d 'run one turn and print the answer'
complete -c yi -n __fish_use_subcommand -a sessions -d 'list, show, or remove stored sessions'
complete -c yi -n __fish_use_subcommand -a undo -d 'restore the files the last turn changed'
complete -c yi -n __fish_use_subcommand -a rpc -d 'speak the Pi JSON-RPC protocol on stdio'
complete -c yi -n __fish_use_subcommand -a acp -d 'speak ACP v2 on stdio'
complete -c yi -n __fish_use_subcommand -a serve -d 'run the session daemon'
complete -c yi -n __fish_use_subcommand -a tui -d 'open the terminal UI'
complete -c yi -n __fish_use_subcommand -a mcp -d 'one-shot MCP client calls'
complete -c yi -n __fish_use_subcommand -a version -d 'print the version'
complete -c yi -n '__fish_seen_subcommand_from sessions' -a 'list show rm'
complete -c yi -l model -r -d 'provider/id'
complete -c yi -l system -r -d 'extra system prompt'
complete -c yi -l thinking -r -a 'off minimal low medium high' -d 'thinking level'
complete -c yi -l json -d 'emit the event stream as JSON'
complete -c yi -l yolo -d 'skip permission prompts'
complete -c yi -l session -r -d 'resume this session id'
complete -c yi -l session-dir -r -F -d 'session storage root'
complete -c yi -l continue -d 'resume the newest session for this directory'
complete -c yi -l schema -r -F -d 'validate the answer against a JSON Schema'
complete -c yi -l cwd -r -F -d 'working directory'
complete -c yi -l socket -r -F -d 'daemon socket path'
complete -c yi -l headless -d 'drive the TUI without a terminal'
complete -c yi -l keys -r -F -d 'TUI key script'
complete -c yi -l frames -r -F -d 'TUI frame dump directory'
